-- MySQL Script generated by MySQL Workbench
-- Sat Mar 28 15:12:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tab_filial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tab_filial` (
  `tfi_id` INT NOT NULL AUTO_INCREMENT,
  `tfi_nome` VARCHAR(45) NOT NULL,
  `tfi_endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tfi_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tab_cad_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tab_cad_produto` (
  `tcp_codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tcp_codigo_barras` INT UNSIGNED NOT NULL,
  `tcp_descricao` VARCHAR(45) NOT NULL,
  `tcp_quantidade_estoque` INT UNSIGNED NOT NULL,
  `tcp_valor` DOUBLE NOT NULL,
  `tab_filial_tfi_id` INT NOT NULL,
  PRIMARY KEY (`tcp_codigo`),
  INDEX `fk_tab_cad_produto_tab_filial1_idx` (`tab_filial_tfi_id` ASC) VISIBLE,
  CONSTRAINT `fk_tab_cad_produto_tab_filial1`
    FOREIGN KEY (`tab_filial_tfi_id`)
    REFERENCES `mydb`.`tab_filial` (`tfi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tab_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tab_usuario` (
  `tus_id` INT NOT NULL AUTO_INCREMENT,
  `tus_login` VARCHAR(45) NOT NULL,
  `tus_senha` VARCHAR(45) NOT NULL,
  `tus_nome` VARCHAR(45) NOT NULL,
  `tab_filial_tfi_id` INT NOT NULL,
  PRIMARY KEY (`tus_id`),
  INDEX `fk_tab_usuario_tab_filial1_idx` (`tab_filial_tfi_id` ASC) VISIBLE,
  CONSTRAINT `fk_tab_usuario_tab_filial1`
    FOREIGN KEY (`tab_filial_tfi_id`)
    REFERENCES `mydb`.`tab_filial` (`tfi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tab_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tab_pedido` (
  `tpd_id` INT NOT NULL AUTO_INCREMENT,
  `tpd_tipo_pedido` INT NOT NULL,
  `tpd_cliente` VARCHAR(45) NULL,
  `tpd_observacao` TEXT NULL,
  `tpd_hora_aberto` TIMESTAMP NOT NULL DEFAULT time.now(),
  `tpd_hora_fechado` TIMESTAMP NULL,
  `tpd_status_pedido` INT NOT NULL,
  `tpd_forma_pagamento` INT NULL,
  `tab_filial_tfi_id` INT NOT NULL,
  `tab_usuario_tus_id` INT NOT NULL,
  PRIMARY KEY (`tpd_id`),
  INDEX `fk_tab_pedido_tab_filial_idx` (`tab_filial_tfi_id` ASC) VISIBLE,
  INDEX `fk_tab_pedido_tab_usuario1_idx` (`tab_usuario_tus_id` ASC) VISIBLE,
  CONSTRAINT `fk_tab_pedido_tab_filial`
    FOREIGN KEY (`tab_filial_tfi_id`)
    REFERENCES `mydb`.`tab_filial` (`tfi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_pedido_tab_usuario1`
    FOREIGN KEY (`tab_usuario_tus_id`)
    REFERENCES `mydb`.`tab_usuario` (`tus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tab_pedido_has_tab_cad_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tab_pedido_has_tab_cad_produto` (
  `tab_pedido_tpd_id` INT NOT NULL,
  `tab_cad_produto_tcp_codigo` INT UNSIGNED NOT NULL,
  `tpd_tcp_quantidade_pedida` INT UNSIGNED NOT NULL,
  `tpp_status_item` INT NOT NULL,
  PRIMARY KEY (`tab_pedido_tpd_id`, `tab_cad_produto_tcp_codigo`),
  INDEX `fk_tab_pedido_has_tab_cad_produto_tab_cad_produto1_idx` (`tab_cad_produto_tcp_codigo` ASC) VISIBLE,
  INDEX `fk_tab_pedido_has_tab_cad_produto_tab_pedido1_idx` (`tab_pedido_tpd_id` ASC) VISIBLE,
  CONSTRAINT `fk_tab_pedido_has_tab_cad_produto_tab_pedido1`
    FOREIGN KEY (`tab_pedido_tpd_id`)
    REFERENCES `mydb`.`tab_pedido` (`tpd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_pedido_has_tab_cad_produto_tab_cad_produto1`
    FOREIGN KEY (`tab_cad_produto_tcp_codigo`)
    REFERENCES `mydb`.`tab_cad_produto` (`tcp_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
